### PR TITLE
Fix SVGElement.viewportElement

### PR DESCRIPTION
**Pull request by biojet1**
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement) _SVGElement.viewportElement_ is the nearest **ancestor** <svg> element, ownerSVGElement also

### CODE REVIEW

**Comment by Fuzzyma** [comment]
please adhere to the coding style. Otherwise I cant really see what you changed because every line is red

**Comment by biojet1** [comment]
I made a mistake so I committed again, I also adjusted the style

The fix was the **viewportElement** and **ownerSVGElement** method returns the **farthest** `svg` ancestor element.

The specs says the nearest

**Comment by Fuzzyma** [comment]
haha now this or makes much more sense :D.
Can you get rid of the semicoli? Then I can merge :).
Thank you!!

**Comment by biojet1** [comment]
Semicolons removed

**Pull request merged**
