### PR TITLE
Correctly calculate an arc's centre point

### LINKED ISSUE #35: Call stack exceeded when getting the length of a circular path
The following results in `RangeError: Maximum call stack size exceeded`:

```
const window = require('svgdom')
const document = window.document
const {SVG, registerWindow} = require('@svgdotjs/svg.js')

registerWindow(window , window.document)

const canvas = SVG(document.documentElement)

// A circular path
const path = canvas.path('M0.5 50a49.5 49.5 0 1 0 99 0 49.5 49.5 0 1 0-99 0');

// Gets RangeError: Maximum call stack size exceeded
const len = path.length();
```

### PR DESCRIPTION
**Pull request by dbrnz**
This fixes #35.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Really? It was a missing `this`?? Did I miss something or is that the whole solution? :D

**Comment by dbrnz** [comment]
Yes, that was all! Otherwise this comparison for the `new Arc()` constructors called from `splitAt()` were comparing a boolean and an integer. This will always be `false`.

**Comment by Fuzzyma** [comment]
That means you were completely right when you pointed out your guess about the one commit which broke it - because we converted those variables :D

**Comment by dbrnz** [comment]
Intuition and many decades of debugging software :-)

**Comment by Fuzzyma** [comment]
Jeah I guess :D. I will merge that when iam home! Thank you very much!

**Pull request merged**
