### PR TITLE
fixed typo: HTMLLinkElement is <link>, not <a>

### PR DESCRIPTION
**Pull request by michael-brade**

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Oh, right. I am not sure who added it. I always assumed whoever did it meaned a hyperlink. Where is it used?

**Comment by michael-brade** [comment]
Gee, you are fast!

Hehe, it was me :-) I added it for LaTeX.js, I use it to add stylesheets to the generated document.

**Comment by michael-brade** [comment]
See `stylesAndScripts` here: https://github.com/michael-brade/LaTeX.js/blob/master/src/html-generator.ls#L247

**Comment by Fuzzyma** [comment]
Cool! :)
Jeah - I was at my computer anyway. But for the next response you have to wait until tomorrow ^^

**Comment by michael-brade** [comment]
:-)
Well, we could add a `HTMLAnchorElement`, just for good measure... and for reduced confusion ;-)

**Comment by Fuzzyma** [comment]
Wow, I do this for that long now but I didn't know that this is the official name for a link :D.
I don't really think we need it. Yes we have links in svg too but they don't have special behaviors so they they can default to just SVGElement ^^

**Pull request merged**
